src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Vich\UploaderBundle\Entity\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=ImageRepository::class)
 * @Vich\Uploadable()
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file_name;



    /**
     * @ORM\ManyToOne(targetEntity=ProductsAndServices::class, inversedBy="images")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    public ?ProductsAndServices $product;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $isActive;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title;

    /**
     * @Vich\UploadableField(mapping="thumbnails", fileNameProperty="file_name")
     * @var File
     */
    private $thumbnail;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getProductId(): ?ProductsAndServices
    {
        return $this->product;
    }

    public function setProductId(?ProductsAndServices $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getProduct(): ?ProductsAndServices
    {
        return $this->product;
    }


    public function setProduct(?ProductsAndServices $product): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getThumbnail(): mixed
    {
        return $this->thumbnail;
    }

    /**
     * @param \Symfony\Component\HttpFoundation\File\File|null $thumbnail
     */
    public function setThumbnail(\Symfony\Component\HttpFoundation\File\File $thumbnail = null): void
    {
        $this->thumbnail = $thumbnail;
        if ($thumbnail) {
            $this->createdAt = new DateTime();
        }
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    public function __toString() {
        return $this->title;
    }

}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 * @ORM\EntityListeners({"App\EventListener\OrderCreateListener", "App\EventListener\OrderEditListener"})
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $post_code;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $order_number;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=ProductOrderList::class, mappedBy="order_id", cascade={"persist", "remove"})
     */
    private $productOrderLists;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2, nullable=true)
     */
    private $order_total;

    public function __construct()
    {
        $this->productOrderLists = new ArrayCollection();
        $this->order_number = self::uniqOrderNumber();
        $this->date = new DateTime('Europe/Vilnius');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(string $post_code): self
    {
        $this->post_code = $post_code;

        return $this;
    }

    public function getOrderNumber(): ?string
    {
        return $this->order_number;
    }

    public function setOrderNumber(string $order_number): self
    {
        $this->order_number = $order_number;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getProductOrderLists(): ?Collection
    {
        return $this->productOrderLists;
    }

    public function addProductOrderList(ProductOrderList $productOrderList): self
    {
        if (!$this->productOrderLists->contains($productOrderList)) {
            $this->productOrderLists[] = $productOrderList;
            $productOrderList->setOrderId($this);
        }

        return $this;
    }

    public function removeProductOrderList(ProductOrderList $productOrderList): self
    {
        if ($this->productOrderLists->removeElement($productOrderList)) {
            // set the owning side to null (unless already changed)
            if ($productOrderList->getOrderId() === $this) {
                $productOrderList->setOrderId(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __toString()
    {
        return $this->order_number;
    }

    public function uniqOrderNumber()
    {
        $this->order_number = time() . $this->id . mt_rand(1, 100000000);
        return $this->order_number;
    }

    public function getOrderTotal(): ?string
    {
        return $this->order_total;
    }

    public function setOrderTotal(?string $order_total): self
    {
        $this->order_total = $order_total;

        return $this;
    }
}

templates/pages/cart.html.twig
{% extends"base.html.twig" %}
{% block body %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->
    {% if app.user and cart %}
<!-- Cart Start -->
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                            <tr>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Remove</th>
                            </tr>
                            </thead>
                            {% set totalAmount, shipping = 0, 1 %}
                            <tbody class="align-middle">
                            {% for item in cart %}
                                {% set totalAmount = totalAmount + item.total %}
                            <tr class="cart-item-full">
                                <td>
                                    <div class="img">
                                        <a href="#"><img src="{{ asset('uploads/images/') }}{{ item.product.MainImage is not empty ? item.product.MainImage.FileName : '#' }}" alt="{{ item.product.title }}"></a>
                                        <p>{{ item.product.title }}</p>
                                    </div>
                                 </td>
                                <td>{{ item.product.getCurrentPrice(pm)|format_currency('EUR') }}</td>
                                <td>
                                    <div class="qty">
                                        <button class="btn-minus cart-amount" data-cart="{{ item.id }}" data-product="{{ item.product.id }}" data-user="{{ app.user.id }}" data-direction="minus">
                                            <i class="fa fa-minus"></i></button>
                                        {% set uniqId = "%sABC"|format(item.id) %}
                                        <input readonly data-counter="{{uniqId}}" id="{{uniqId}}" class="current-amount" type="text" value="{{ item.quantity }}">
                                        <button class="btn-plus cart-amount" data-cart="{{ item.id }}" data-product="{{ item.product.id }}" data-user="{{ app.user.id }}" data-direction="plus">
                                            <i class="fa fa-plus"></i></button>
                                    </div>
                                </td>
                                <td><span id="{{ item.id }}">{{ item.total|format_currency('EUR') }}</span></td>
                                <td>
                                    <form action="{{ path('cart_remove', {product : item.product.id}) }}" method="post">
                                        <button name="foo" value="{{ item.product.id }}"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
{#                                <button><a href="{{ path('cart_remove', {'product' : item.product.id}) }}"><i class="fa fa-trash"></i></a></button>#}
                            </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="cart-summary">
                                <div class="cart-content">
                                    <h1>Cart Summary</h1>
                                    <p>Sub Total<span>{{ totalAmount | format_currency('EUR') }}</span></p>
                                    <p>Shipping Cost<span>{{ shipping | format_currency('EUR') }}</span></p>
                                    {% set finalTotal = totalAmount + shipping  %}
                                    <h2>Grand Total<span>{{ finalTotal | format_currency('EUR') }}</span></h2>
                                </div>
                                <div class="cart-btn">
                                    <button><a style="color: #0a0a0a" href="{{ path('pages/cart')}}">Update Cart</a></button>
                                    <button><a style="color:white" href="{{ path('pages/checkout') }}">Checkout</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                            {% endif %}
<!-- Cart End -->
{% endblock %}

templates/pages/contact.html.twig
{% extends"base.html.twig" %}
{% block body %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Contact</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Contact Start -->
<div class="contact">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
                <div class="contact-info">
                    <h2>Our Office</h2>
                    <h3><i class="fa fa-map-marker"></i>123 Office, Los Angeles, CA, USA</h3>
                    <h3><i class="fa fa-envelope"></i>office@example.com</h3>
                    <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                    <div class="social">
                        <a href=""><i class="fab fa-twitter"></i></a>
                        <a href=""><i class="fab fa-facebook-f"></i></a>
                        <a href=""><i class="fab fa-linkedin-in"></i></a>
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-info">
                    <h2>Our Store</h2>
                    <h3><i class="fa fa-map-marker"></i>123 Store, Los Angeles, CA, USA</h3>
                    <h3><i class="fa fa-envelope"></i>store@example.com</h3>
                    <h3><i class="fa fa-phone"></i>+123-456-7890</h3>
                    <div class="social">
                        <a href=""><i class="fab fa-twitter"></i></a>
                        <a href=""><i class="fab fa-facebook-f"></i></a>
                        <a href=""><i class="fab fa-linkedin-in"></i></a>
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-youtube"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="contact-form">
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" placeholder="Your Name" />
                            </div>
                            <div class="col-md-6">
                                <input type="email" class="form-control" placeholder="Your Email" />
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Subject" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" rows="5" placeholder="Message"></textarea>
                        </div>
                        <div><button class="btn" type="submit">Send Message</button></div>
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="contact-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4739.936338279641!2d25.26238103633693!3d54.75359884818221!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dd911d574e3199%3A0x762b0add22c1969b!2sBaltic%20Amadeus!5e0!3m2!1slt!2slt!4v1628372796164!5m2!1slt!2slt" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock %}

templates/pages/login.html.twig
{% extends"base.html.twig" %}
{% block body %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">Login & Register</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Login Start -->
<div class="login">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="register-form">
                    <div class="row">
                        <div class="col-md-6">
                            <label>First Name</label>
                            <input class="form-control" type="text" placeholder="First Name">
                        </div>
                        <div class="col-md-6">
                            <label>Last Name"</label>
                            <input class="form-control" type="text" placeholder="Last Name">
                        </div>
                        <div class="col-md-6">
                            <label>E-mail</label>
                            <input class="form-control" type="text" placeholder="E-mail">
                        </div>
                        <div class="col-md-6">
                            <label>Mobile No</label>
                            <input class="form-control" type="text" placeholder="Mobile No">
                        </div>
                        <div class="col-md-6">
                            <label>Password</label>
                            <input class="form-control" type="text" placeholder="Password">
                        </div>
                        <div class="col-md-6">
                            <label>Retype Password</label>
                            <input class="form-control" type="text" placeholder="Password">
                        </div>
                        <div class="col-md-12">
                            <button class="btn">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="login-form">
                    <div class="row">
                        <div class="col-md-6">
                            <label>E-mail / Username</label>
                            <input class="form-control" type="text" placeholder="E-mail / Username">
                        </div>
                        <div class="col-md-6">
                            <label>Password</label>
                            <input class="form-control" type="text" placeholder="Password">
                        </div>
                        <div class="col-md-12">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="newaccount">
                                <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button class="btn">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Login End -->
{% endblock %}

templates/pages/my_account.html.twig
{% extends"base.html.twig" %}
{% block body %}
<!-- Breadcrumb Start -->
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Products</a></li>
            <li class="breadcrumb-item active">My Account</li>
        </ul>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- My Account Start -->
<div class="my-account">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">

                    <a class="nav-link {{ orders is defined and orders is not null ? 'active' : '' }}" id="orders-nav"
                       data-toggle="pill" href="#orders-tab" role="tab" {{ orders is defined and orders is not null ? 'aria-selected="true"' : 'aria-selected="false"' }}><i class="fa fa-shopping-bag"></i>Orders</a>
                    <a class="nav-link" id="payment-nav" data-toggle="pill" href="#payment-tab" role="tab"><i class="fa fa-credit-card"></i>Payment Method</a>
                    <a class="nav-link" id="address-nav" data-toggle="pill" href="#address-tab" role="tab"><i class="fa fa-map-marker-alt"></i>address</a>
                    <a class="nav-link" id="account-nav" data-toggle="pill" href="#account-tab" role="tab"><i class="fa fa-user"></i>Account Details</a>
                    <a class="nav-link" href="{{ path('home') }}"><i class="fa fa-sign-out-alt"></i>Logout</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="orders-tab" role="tabpanel" aria-labelledby="orders-nav">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Order nr.</th>
                                    <th>Date</th>
                                    <th>Total</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if orders is defined and orders is not null %}
                                {% for order in orders |sort((a, b) => b.date <=> a.date) %}
                                <tr>
                                    <td>{{order.orderNumber}}</td>
                                    <td>{{ order.date |format_datetime() }}</td>
                                    <td>{{ order.orderTotal | format_currency('EUR') }}</td>
                                    <td>{{ order.status is same as true ? 'Approved' : 'Pending' }}</td>
                                    <td><a href="{{ path('pages/show_order', {'id' : order.id}) }}"><button class="btn">View</button></a></td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="payment-tab" role="tabpanel" aria-labelledby="payment-nav">
                        <h4>Payment Method</h4>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum quam ac mi viverra dictum. In efficitur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus. Nulla tristique viverra nisl, sit amet bibendum ante suscipit non. Praesent in faucibus tellus, sed gravida lacus. Vivamus eu diam eros. Aliquam et sapien eget arcu rhoncus scelerisque.
                        </p>
                    </div>
                    <div class="tab-pane fade" id="address-tab" role="tabpanel" aria-labelledby="address-nav">
                        <h4>Address</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <h5>Payment Address</h5>
                                <p>123 Payment Street, Los Angeles, CA</p>
                                <p>Mobile: 012-345-6789</p>
                                <button class="btn">Edit Address</button>
                            </div>
                            <div class="col-md-6">
                                <h5>Shipping Address</h5>
                                <p>123 Shipping Street, Los Angeles, CA</p>
                                <p>Mobile: 012-345-6789</p>
                                <button class="btn">Edit Address</button>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-tab" role="tabpanel" aria-labelledby="account-nav">
                        <h4>Account Details</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="First Name">
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="Last Name">
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="Mobile">
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="Email">
                            </div>
                            <div class="col-md-12">
                                <input class="form-control" type="text" placeholder="Address">
                            </div>
                            <div class="col-md-12">
                                <button class="btn">Update Account</button>
                                <br><br>
                            </div>
                        </div>
                        <h4>Password change</h4>
                        <div class="row">
                            <div class="col-md-12">
                                <input class="form-control" type="password" placeholder="Current Password">
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="New Password">
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" type="text" placeholder="Confirm Password">
                            </div>
                            <div class="col-md-12">
                                <button class="btn">Save Changes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- My Account End -->
{% endblock %}

templates/pages/show_order.html.twig
{% extends"base.html.twig" %}
{% block body %}
    {% if order is not null %}
        <div class="col-md-8" style="margin: auto">
            <h5 style="font-weight: 600">Order details</h5>
            <p><strong>Order number : </strong>{{ order.orderNumber }}</p>
            <p><strong>Date : </strong>{{ order.date |format_datetime() }}</p>
            <p><strong>Total : </strong>{{ order.orderTotal | format_currency('EUR') }}<p>
        </div>
    {% endif %}
        <div class="col-md-8" style="margin: auto">
            <div class="table-responsive">
                <table class="table table-bordered" style="text-align: center">
                    <thead class="thead-dark">
                    <tr>
                        <th>View</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if productOrderLists is not null %}
                        {% for item in productOrderLists %}
                            <tr>
                                <td><img style="width: 50px; height: 50px; margin: auto"
                                         src="{{ asset('uploads/images/') }}{{ item.product.mainImage.fileName }}"
                                         alt="{{ item.product.mainImage }}"/></td>
                                <td>{{ item.product.title }}</td>
                                <td>{{ item.quantity|number_format(2, '.', ',') }}</td>
                                <td>{{ item.price | format_currency('EUR') }}</td>
                                <td>{{ item.total | format_currency('EUR') }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}